#创建库
CREATE DATABASE SSM;
#使用库
USER SSM;
#创建用户表
CREATE TABLE TB_USER(
	ROW_ID BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT'主键',
	USER_NAME VARCHAR(30) NOT NULL COMMENT'用户名称',
	USER_CODE VARCHAR(30) NOT NULL UNIQUE COMMENT'用户账号',
	USER_PASSWORD VARBINARY(60) NOT NULL COMMENT'用户密码',
	USER_AVATAR VARCHAR(120) COMMENT'用户头像',
	LOGIN_COUNT INT COMMENT'登录次数',
	LAST_LOGIN_IP VARCHAR(20) COMMENT'最后的登录ip',
	LAST_LOGIN_DATE DATE COMMENT'最后登录时间',
	IS_LOCK INT COMMENT '是否锁定',
	`ACTIVE_FLAG` INT(11) DEFAULT NULL COMMENT '数据是否有效：1有效 0无效',
	`CREATE_BY` VARCHAR(30) DEFAULT NULL COMMENT '创建人',
	`CREATE_DATE` DATE DEFAULT NULL COMMENT '创建时间',
	`UPDATE_BY` VARCHAR(30) DEFAULT NULL COMMENT '修改人',
	`UPDATE_DATE` DATE DEFAULT NULL COMMENT '修改时间'
 )ENGINE=INNODB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8 COMMENT='用户表';